export const customerConstants = {
  CREATE_REQUEST: "CUSTOMERS_CREATE_REQUEST",
  CREATE_SUCCESS: "CUSTOMERS_CREATE_SUCCESS",
  CREATE_FAILURE: "CUSTOMERS_CREATE_FAILURE",

  GET_REQUEST: "CUSTOMERS_GET_REQUEST",
  GET_SUCCESS: "CUSTOMERS_GET_SUCCESS",
  GET_FAILURE: "CUSTOMERS_GET_FAILURE",

  GET_ALL_REQUEST: "CUSTOMERS_GET_ALL_REQUEST",
  GET_ALL_SUCCESS: "CUSTOMERS_GET_ALL_SUCCESS",
  GET_ALL_FAILURE: "CUSTOMERS_GET_ALL_FAILURE",

  GET_FILTER_REQUEST: "CUSTOMERS_GET_FILTER_REQUEST",
  GET_FILTER_SUCCESS: "CUSTOMERS_GET_FILTER_SUCCESS",
  GET_FILTER_FAILURE: "CUSTOMERS_GET_FILTER_FAILURE",

  GET_BY_SEQUENCE_REQUEST: "CUSTOMERS_GET_BY_SEQUENCE_REQUEST",
  GET_BY_SEQUENCE_SUCCESS: "CUSTOMERS_GET_BY_SEQUENCE_SUCCESS",
  GET_BY_SEQUENCE_FAILURE: "CUSTOMERS_GET_BY_SEQUENCE_FAILURE",


  UPDATE_REQUEST: "CUSTOMERS_UPDATE_REQUEST",
  UPDATE_SUCCESS: "CUSTOMERS_UPDATE_SUCCESS",
  UPDATE_FAILURE: "CUSTOMERS_UPDATE_FAILURE",

  VERIFY_REQUEST: "CUSTOMERS_VERIFY_REQUEST",
  VERIFY_SUCCESS: "CUSTOMERS_VERIFY_SUCCESS",
  VERIFY_FAILURE: "CUSTOMERS_VERIFY_FAILURE",

  REMOVE_REQUEST: "CUSTOMERS_REMOVE_REQUEST",
  REMOVE_SUCCESS: "CUSTOMERS_REMOVE_SUCCESS",
  REMOVE_FAILURE: "CUSTOMERS_REMOVE_FAILURE",

  GET_SIGNATURE_REQUEST: "CUSTOMERS_GET_SIGNATURE_REQUEST",
  GET_SIGNATURE_SUCCESS: "CUSTOMERS_GET_SIGNATURE_SUCCESS",
  GET_SIGNATURE_FAILURE: "CUSTOMERS_GET_SIGNATURE_FAILURE",

  APPROVE_REQUEST: "CUSTOMERS_APPROVE_REQUEST",
  APPROVE_SUCCESS: "CUSTOMERS_APPROVE_SUCCESS",
  APPROVE_FAILURE: "CUSTOMERS_APPROVE_FAILURE",

  REVOKE_APPROVE_REQUEST: "CUSTOMERS_REVOKE_APPROVE_REQUEST",
  REVOKE_APPROVE_SUCCESS: "CUSTOMERS_REVOKE_APPROVE_SUCCESS",
  REVOKE_APPROVE_FAILURE: "CUSTOMERS_REVOKE_APPROVE_FAILURE",

  SET_VERIFY_REQUEST: "CUSTOMERS_SET_VERIFY_REQUEST",
  SET_VERIFY_SUCCESS: "CUSTOMERS_SET_VERIFY_SUCCESS",
  SET_VERIFY_FAILURE: "CUSTOMERS_SET_VERIFY_FAILURE"
};
