export const databaseConstants = {
  SET_COUNTER_REQUEST: "DATABASE_SET_COUNTER_REQUEST",
  SET_COUNTER_SUCCESS: "DATABASE_SET_COUNTER_SUCCESS",
  SET_COUNTER_FAILURE: "DATABASE_SET_COUNTER_FAILURE"

  //   RESET_COUNTER_REQUEST: "DATABASE_RESET_COUNTER_REQUEST",
  //   RESET_COUNTER_SUCCESS: "DATABASE_RESET_COUNTER_SUCCESS",
  //   RESET_COUNTER_FAILURE: "DATABASE_RESET_COUNTER_FAILURE"
};
