export const databaseConstants = {
  GET_ALL_COUNTER_REQUEST: "DATABASE_GET_ALL_COUNTER_REQUEST",
  GET_ALL_COUNTER_SUCCESS: "DATABASE_GET_ALL_COUNTER_SUCCESS",
  GET_ALL_COUNTER_FAILURE: "DATABASE_GET_ALL_COUNTER_FAILURE",

  SET_COUNTER_REQUEST: "DATABASE_SET_COUNTER_REQUEST",
  SET_COUNTER_SUCCESS: "DATABASE_SET_COUNTER_SUCCESS",
  SET_COUNTER_FAILURE: "DATABASE_SET_COUNTER_FAILURE",

  GET_INFO_REQUEST: "DATABASE_GET_INFO_REQUEST",
  GET_INFO_SUCCESS: "DATABASE_GET_INFO_SUCCESS",
  GET_INFO_FAILURE: "DATABASE_GET_INFO_FAILURE"
};
