export const userConstants = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  CREATE_REQUEST: "USERS_CREATE_REQUEST",
  CREATE_SUCCESS: "USERS_CREATE_SUCCESS",
  CREATE_FAILURE: "USERS_CREATE_FAILURE",

  GET_REQUEST: "USERS_GET_REQUEST",
  GET_SUCCESS: "USERS_GET_SUCCESS",
  GET_FAILURE: "USERS_GET_FAILURE",

  GET_ALL_REQUEST: "USERS_GET_ALL_REQUEST",
  GET_ALL_SUCCESS: "USERS_GET_ALL_SUCCESS",
  GET_ALL_FAILURE: "USERS_GET_ALL_FAILURE",

  GET_FILTER_REQUEST: "USERS_GET_FILTER_REQUEST",
  GET_FILTER_SUCCESS: "USERS_GET_FILTER_SUCCESS",
  GET_FILTER_FAILURE: "USERS_GET_FILTER_FAILURE",

  UPDATE_REQUEST: "USERS_UPDATE_REQUEST",
  UPDATE_SUCCESS: "USERS_UPDATE_SUCCESS",
  UPDATE_FAILURE: "USERS_UPDATE_FAILURE",

  REMOVE_REQUEST: "USERS_REMOVE_REQUEST",
  REMOVE_SUCCESS: "USERS_REMOVE_SUCCESS",
  REMOVE_FAILURE: "USERS_REMOVE_FAILURE"
};
